version: '3'
services:
  stegano:
    container_name: stegano
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      
  caddy:
    image: caddy:2.7.6
    container_name: caddy
    command: caddy reverse-proxy --from https://stegano.radatuli.shop:443 --to http://stegano:3000
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - data:/data
      - config:/config

volumes:
  data:
  config:
